export type CountryOption = { code: string; name: string; dial: string };

// Minimal-risk static dataset: ISO-like country codes + names + dial prefix.
// Used only for client-side selects (no styling impact).
export const COUNTRIES: CountryOption[] = [
  { code: "AF", name: "Afeganistão", dial: "+93" },
  { code: "ZA", name: "África do Sul", dial: "+27" },
  { code: "AL", name: "Albânia", dial: "+355" },
  { code: "DE", name: "Alemanha", dial: "+49" },
  { code: "AD", name: "Andorra", dial: "+376" },
  { code: "AO", name: "Angola", dial: "+244" },
  { code: "AI", name: "Anguila", dial: "+1" },
  { code: "AG", name: "Antígua e Barbuda", dial: "+1" },
  { code: "SA", name: "Arábia Saudita", dial: "+966" },
  { code: "DZ", name: "Argélia", dial: "+213" },
  { code: "AR", name: "Argentina", dial: "+54" },
  { code: "AM", name: "Arménia", dial: "+374" },
  { code: "AW", name: "Aruba", dial: "+297" },
  { code: "AU", name: "Austrália", dial: "+61" },
  { code: "AT", name: "Áustria", dial: "+43" },
  { code: "AZ", name: "Azerbaijão", dial: "+994" },
  { code: "BS", name: "Bahamas", dial: "+1" },
  { code: "BH", name: "Barém", dial: "+973" },
  { code: "BD", name: "Bangladesh", dial: "+880" },
  { code: "BB", name: "Barbados", dial: "+1" },
  { code: "BE", name: "Bélgica", dial: "+32" },
  { code: "BZ", name: "Belize", dial: "+501" },
  { code: "BJ", name: "Benim", dial: "+229" },
  { code: "BM", name: "Bermudas", dial: "+1" },
  { code: "BY", name: "Bielorrússia", dial: "+375" },
  { code: "BO", name: "Bolívia", dial: "+591" },
  { code: "BA", name: "Bósnia e Herzegovina", dial: "+387" },
  { code: "BW", name: "Botsuana", dial: "+267" },
  { code: "BR", name: "Brasil", dial: "+55" },
  { code: "BN", name: "Brunei", dial: "+673" },
  { code: "BG", name: "Bulgária", dial: "+359" },
  { code: "BF", name: "Burquina Faso", dial: "+226" },
  { code: "BI", name: "Burundi", dial: "+257" },
  { code: "CV", name: "Cabo Verde", dial: "+238" },
  { code: "CM", name: "Camarões", dial: "+237" },
  { code: "KH", name: "Camboja", dial: "+855" },
  { code: "CA", name: "Canadá", dial: "+1" },
  { code: "QA", name: "Catar", dial: "+974" },
  { code: "KZ", name: "Cazaquistão", dial: "+7" },
  { code: "TD", name: "Chade", dial: "+235" },
  { code: "CL", name: "Chile", dial: "+56" },
  { code: "CN", name: "China", dial: "+86" },
  { code: "CY", name: "Chipre", dial: "+357" },
  { code: "CO", name: "Colômbia", dial: "+57" },
  { code: "KM", name: "Comores", dial: "+269" },
  { code: "CG", name: "Congo", dial: "+242" },
  { code: "CD", name: "Congo (RDC)", dial: "+243" },
  { code: "KP", name: "Coreia do Norte", dial: "+850" },
  { code: "KR", name: "Coreia do Sul", dial: "+82" },
  { code: "CR", name: "Costa Rica", dial: "+506" },
  { code: "CI", name: "Costa do Marfim", dial: "+225" },
  { code: "HR", name: "Croácia", dial: "+385" },
  { code: "CU", name: "Cuba", dial: "+53" },
  { code: "DK", name: "Dinamarca", dial: "+45" },
  { code: "DJ", name: "Djibuti", dial: "+253" },
  { code: "DM", name: "Dominica", dial: "+1" },
  { code: "EG", name: "Egito", dial: "+20" },
  { code: "SV", name: "El Salvador", dial: "+503" },
  { code: "AE", name: "Emirados Árabes Unidos", dial: "+971" },
  { code: "EC", name: "Equador", dial: "+593" },
  { code: "ER", name: "Eritreia", dial: "+291" },
  { code: "SK", name: "Eslováquia", dial: "+421" },
  { code: "SI", name: "Eslovénia", dial: "+386" },
  { code: "ES", name: "Espanha", dial: "+34" },
  { code: "US", name: "Estados Unidos", dial: "+1" },
  { code: "EE", name: "Estónia", dial: "+372" },
  { code: "ET", name: "Etiópia", dial: "+251" },
  { code: "FJ", name: "Fiji", dial: "+679" },
  { code: "PH", name: "Filipinas", dial: "+63" },
  { code: "FI", name: "Finlândia", dial: "+358" },
  { code: "FR", name: "França", dial: "+33" },
  { code: "GA", name: "Gabão", dial: "+241" },
  { code: "GM", name: "Gâmbia", dial: "+220" },
  { code: "GH", name: "Gana", dial: "+233" },
  { code: "GE", name: "Geórgia", dial: "+995" },
  { code: "GD", name: "Granada", dial: "+1" },
  { code: "GR", name: "Grécia", dial: "+30" },
  { code: "GL", name: "Gronelândia", dial: "+299" },
  { code: "GT", name: "Guatemala", dial: "+502" },
  { code: "GY", name: "Guiana", dial: "+592" },
  { code: "GN", name: "Guiné", dial: "+224" },
  { code: "GQ", name: "Guiné Equatorial", dial: "+240" },
  { code: "GW", name: "Guiné-Bissau", dial: "+245" },
  { code: "HT", name: "Haiti", dial: "+509" },
  { code: "HN", name: "Honduras", dial: "+504" },
  { code: "HU", name: "Hungria", dial: "+36" },
  { code: "YE", name: "Iémen", dial: "+967" },
  { code: "IN", name: "Índia", dial: "+91" },
  { code: "ID", name: "Indonésia", dial: "+62" },
  { code: "IR", name: "Irão", dial: "+98" },
  { code: "IQ", name: "Iraque", dial: "+964" },
  { code: "IE", name: "Irlanda", dial: "+353" },
  { code: "IS", name: "Islândia", dial: "+354" },
  { code: "IL", name: "Israel", dial: "+972" },
  { code: "IT", name: "Itália", dial: "+39" },
  { code: "JM", name: "Jamaica", dial: "+1" },
  { code: "JP", name: "Japão", dial: "+81" },
  { code: "JO", name: "Jordânia", dial: "+962" },
  { code: "KE", name: "Quénia", dial: "+254" },
  { code: "KW", name: "Kuwait", dial: "+965" },
  { code: "LA", name: "Laos", dial: "+856" },
  { code: "LV", name: "Letónia", dial: "+371" },
  { code: "LB", name: "Líbano", dial: "+961" },
  { code: "LR", name: "Libéria", dial: "+231" },
  { code: "LY", name: "Líbia", dial: "+218" },
  { code: "LI", name: "Listenstaine", dial: "+423" },
  { code: "LT", name: "Lituânia", dial: "+370" },
  { code: "LU", name: "Luxemburgo", dial: "+352" },
  { code: "MK", name: "Macedónia do Norte", dial: "+389" },
  { code: "MG", name: "Madagáscar", dial: "+261" },
  { code: "MY", name: "Malásia", dial: "+60" },
  { code: "MW", name: "Malawi", dial: "+265" },
  { code: "MV", name: "Maldivas", dial: "+960" },
  { code: "ML", name: "Mali", dial: "+223" },
  { code: "MT", name: "Malta", dial: "+356" },
  { code: "MA", name: "Marrocos", dial: "+212" },
  { code: "MU", name: "Maurícia", dial: "+230" },
  { code: "MR", name: "Mauritânia", dial: "+222" },
  { code: "MX", name: "México", dial: "+52" },
  { code: "MZ", name: "Moçambique", dial: "+258" },
  { code: "MD", name: "Moldávia", dial: "+373" },
  { code: "MC", name: "Mónaco", dial: "+377" },
  { code: "MN", name: "Mongólia", dial: "+976" },
  { code: "ME", name: "Montenegro", dial: "+382" },
  { code: "NA", name: "Namíbia", dial: "+264" },
  { code: "NP", name: "Nepal", dial: "+977" },
  { code: "NI", name: "Nicarágua", dial: "+505" },
  { code: "NE", name: "Níger", dial: "+227" },
  { code: "NG", name: "Nigéria", dial: "+234" },
  { code: "NO", name: "Noruega", dial: "+47" },
  { code: "NZ", name: "Nova Zelândia", dial: "+64" },
  { code: "OM", name: "Omã", dial: "+968" },
  { code: "NL", name: "Países Baixos", dial: "+31" },
  { code: "PK", name: "Paquistão", dial: "+92" },
  { code: "PA", name: "Panamá", dial: "+507" },
  { code: "PY", name: "Paraguai", dial: "+595" },
  { code: "PE", name: "Peru", dial: "+51" },
  { code: "PL", name: "Polónia", dial: "+48" },
  { code: "PT", name: "Portugal", dial: "+351" },
  { code: "GB", name: "Reino Unido", dial: "+44" },
  { code: "CZ", name: "República Checa", dial: "+420" },
  { code: "DO", name: "República Dominicana", dial: "+1" },
  { code: "RO", name: "Roménia", dial: "+40" },
  { code: "RU", name: "Rússia", dial: "+7" },
  { code: "SN", name: "Senegal", dial: "+221" },
  { code: "RS", name: "Sérvia", dial: "+381" },
  { code: "SG", name: "Singapura", dial: "+65" },
  { code: "SE", name: "Suécia", dial: "+46" },
  { code: "CH", name: "Suíça", dial: "+41" },
  { code: "TH", name: "Tailândia", dial: "+66" },
  { code: "TR", name: "Turquia", dial: "+90" },
  { code: "UA", name: "Ucrânia", dial: "+380" },
  { code: "UY", name: "Uruguai", dial: "+598" },
  { code: "VE", name: "Venezuela", dial: "+58" },
  { code: "VN", name: "Vietname", dial: "+84" },
];

