const mongoose = require("mongoose");
const Partner = require("../models/Partner");

const CATEGORY_PARTNERS = {
  ginasios: {
    label: "Ginásios",
    partners: [
      {
        id: "fitclub-lisboa",
        name: "FitClub Lisboa",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Saldanha",
        description:
          "Health club premium com musculação, cardio e aulas de grupo.",
        activitiesCount: 12,
        minCredits: 6,
        partnerType: "gym_access",
        openingHours: "06:00 – 23:00",
        creditsPerEntry: 6,
        address: "Av. da República 50",
        city: "Lisboa",
        latitude: 38.7359,
        longitude: -9.1426,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7359,-9.1426",
      },
      {
        id: "bluegym-porto",
        name: "BlueGym Porto",
        imageSrc: "/images/gym-hero.jpg",
        location: "Porto · Boavista",
        description: "Ginásio moderno com foco em treinos funcionais e PT.",
        activitiesCount: 8,
        minCredits: 6,
        partnerType: "gym_access",
        openingHours: "06:00 – 22:00",
        fitlifePassHours: "06:00 – 11:00, 14:00 – 17:00",
        creditsPerEntry: 6,
        address: "Rua da Boavista 120",
        city: "Porto",
        latitude: 41.1642,
        longitude: -8.6882,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1642,-8.6882",
      },
      {
        id: "pulse-fitness-studio",
        name: "Pulse Fitness Studio",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Campo de Ourique",
        description: "Estúdio de fitness com equipamento de última geração e aulas em grupo.",
        activitiesCount: 10,
        minCredits: 6,
        partnerType: "gym_access",
        openingHours: "07:00 – 23:00",
        creditsPerEntry: 6,
        address: "Rua Ferreira Borges 45",
        city: "Lisboa",
        latitude: 38.7192,
        longitude: -9.1682,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7192,-9.1682",
      },
      {
        id: "urban-motion-club",
        name: "Urban Motion Club",
        imageSrc: "/images/gym-hero.jpg",
        location: "Lisboa · Alvalade",
        description: "Ginásio urbano com aulas de dança, yoga e pilates.",
        activitiesCount: 15,
        minCredits: 6,
        partnerType: "gym_access",
        openingHours: "06:00 – 23:00",
        creditsPerEntry: 6,
        address: "Rua Manuel Soares Guedes 1",
        city: "Lisboa",
        latitude: 38.7532,
        longitude: -9.1436,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7532,-9.1436",
      },
    ],
  },
  yoga: {
    label: "Yoga",
    partners: [
      {
        id: "zen-yoga-lisboa",
        name: "Zen Yoga Studio",
        imageSrc: "/images/frontpage-hero.jpg",
        location: "Lisboa · Príncipe Real",
        description: "Estúdio de yoga luminoso com aulas de vinyasa e yin.",
        activitiesCount: 14,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua do Príncipe Real 28",
        city: "Lisboa",
        latitude: 38.7189,
        longitude: -9.1482,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7189,-9.1482",
      },
      {
        id: "yoga-bliss-porto",
        name: "Yoga Bliss Porto",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Porto · Cedofeita",
        description: "Aulas de yoga para todos os níveis num espaço tranquilo.",
        activitiesCount: 10,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua da Cedofeita 200",
        city: "Porto",
        latitude: 41.1512,
        longitude: -8.6156,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1512,-8.6156",
      },
    ],
  },
  pilates: {
    label: "Pilates",
    partners: [
      {
        id: "core-pilates-studio",
        name: "Core Pilates Studio",
        imageSrc: "/images/gym-hero.jpg",
        location: "Lisboa · Chiado",
        description: "Pilates em reformer com sessões individuais e em grupo.",
        activitiesCount: 8,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua Garrett 42",
        city: "Lisboa",
        latitude: 38.7104,
        longitude: -9.1402,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7104,-9.1402",
      },
      {
        id: "balance-pilates-porto",
        name: "Balance Pilates Porto",
        imageSrc: "/images/frontpage-hero.jpg",
        location: "Porto · Foz",
        description: "Pilates clássico e contemporâneo num estúdio à beira-mar.",
        activitiesCount: 6,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua do Passeio Alegre 100",
        city: "Porto",
        latitude: 41.1482,
        longitude: -8.6824,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1482,-8.6824",
      },
    ],
  },
  padel: {
    label: "Padel",
    partners: [
      {
        id: "clube-padel-lisboa",
        name: "Clube Padel Lisboa",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Belém",
        description: "Club de padel com vistas e aulas para todos os níveis.",
        activitiesCount: 6,
        minCredits: 10,
        partnerType: "court_booking",
        address: "Rua da Junqueira 88",
        city: "Lisboa",
        latitude: 38.6982,
        longitude: -9.2086,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.6982,-9.2086",
      },
      {
        id: "arena-padel-studio",
        name: "Arena Padel Studio",
        imageSrc: "/images/gym-hero.jpg",
        location: "Porto · Campanhã",
        description: "Pistas climatizadas e programa de torneios.",
        activitiesCount: 5,
        minCredits: 10,
        partnerType: "court_booking",
        address: "Rua de Campanhã 200",
        city: "Porto",
        latitude: 41.1624,
        longitude: -8.5822,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1624,-8.5822",
      },
      {
        id: "smash-court-club",
        name: "Smash Court Club",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Belém",
        description: "Club de padel com vistas e aulas para todos os níveis.",
        activitiesCount: 6,
        minCredits: 10,
        partnerType: "court_booking",
        address: "Rua da Junqueira 88",
        city: "Lisboa",
        latitude: 38.6982,
        longitude: -9.2086,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.6982,-9.2086",
      },
    ],
  },
  spinning: {
    label: "Spinning",
    partners: [
      {
        id: "pulse-cycling",
        name: "Pulse Cycling Studio",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Campo Pequeno",
        description: "Aulas de cycling com música e iluminação imersiva.",
        activitiesCount: 7,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Praça do Campo Pequeno 1",
        city: "Lisboa",
        latitude: 38.7376,
        longitude: -9.1442,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7376,-9.1442",
      },
      {
        id: "reformer-pilates-club",
        name: "Reformer Pilates Club",
        imageSrc: "/images/frontpage-hero.jpg",
        location: "Lisboa · Chiado",
        description: "Pilates em reformer com sessões individuais e em grupo.",
        activitiesCount: 8,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua Garrett 42",
        city: "Lisboa",
        latitude: 38.7104,
        longitude: -9.1402,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7104,-9.1402",
      },
      {
        id: "mind-body-studio",
        name: "Mind & Body Studio",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Porto · Foz",
        description: "HIIT, funcional e recuperação num único espaço.",
        activitiesCount: 8,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua do Passeio Alegre 100",
        city: "Porto",
        latitude: 41.1482,
        longitude: -8.6824,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1482,-8.6824",
      },
      {
        id: "urban-flow-studio",
        name: "Urban Flow Studio",
        imageSrc: "/images/gym-hero.jpg",
        location: "Lisboa · Arroios",
        description: "Aulas de yoga, pilates e meditação num espaço moderno.",
        activitiesCount: 12,
        minCredits: 8,
        partnerType: "class_booking",
        address: "Rua de Arroios 50",
        city: "Lisboa",
        latitude: 38.7262,
        longitude: -9.1336,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7262,-9.1336",
      },
    ],
  },
  "personal-training": {
    label: "Personal Training",
    partners: [
      {
        id: "elite-pt-lisboa",
        name: "Elite PT Lisboa",
        imageSrc: "/images/gym-hero.jpg",
        location: "Lisboa · Saldanha",
        description: "Personal trainers certificados para treinos personalizados.",
        activitiesCount: 5,
        minCredits: 15,
        partnerType: "class_booking",
        provider: {
          type: "trainer",
          specialties: ["Musculação", "Cardio", "Nutrição"],
          certifications: ["NASM", "ACSM"],
          experienceYears: 8,
          bio: "Especialista em treino funcional e nutrição esportiva.",
        },
        address: "Av. da República 50",
        city: "Lisboa",
        latitude: 38.7359,
        longitude: -9.1426,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7359,-9.1426",
      },
      {
        id: "fitcoach-porto",
        name: "FitCoach Porto",
        imageSrc: "/images/frontpage-hero.jpg",
        location: "Porto · Boavista",
        description: "Treinos personalizados com foco em resultados.",
        activitiesCount: 4,
        minCredits: 15,
        partnerType: "class_booking",
        provider: {
          type: "trainer",
          specialties: ["HIIT", "Crossfit", "Reabilitação"],
          certifications: ["CrossFit L1", "FMS"],
          experienceYears: 6,
          bio: "Treinador com experiência em reabilitação e treino de alta intensidade.",
        },
        address: "Rua da Boavista 120",
        city: "Porto",
        latitude: 41.1642,
        longitude: -8.6882,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=41.1642,-8.6882",
      },
    ],
  },
  nutricao: {
    label: "Nutrição",
    partners: [
      {
        id: "nutri-vida-lisboa",
        name: "NutriVida Lisboa",
        imageSrc: "/images/fitness-hero.jpg",
        location: "Lisboa · Campo de Ourique",
        description: "Consultas de nutrição e planos alimentares personalizados.",
        activitiesCount: 3,
        minCredits: 12,
        partnerType: "class_booking",
        provider: {
          type: "trainer",
          specialties: ["Nutrição Esportiva", "Perda de Peso", "Alimentação Saudável"],
          certifications: ["Nutritionist", "Sports Nutrition"],
          experienceYears: 10,
          bio: "Nutricionista especializada em desporto e perda de peso.",
        },
        address: "Rua Ferreira Borges 45",
        city: "Lisboa",
        latitude: 38.7192,
        longitude: -9.1682,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7192,-9.1682",
      },
    ],
  },
  "massagem-desportiva": {
    label: "Massagem Desportiva",
    partners: [
      {
        id: "relax-spa-lisboa",
        name: "Relax Spa Lisboa",
        imageSrc: "/images/gym-hero.jpg",
        location: "Lisboa · Príncipe Real",
        description: "Massagens desportivas e terapêuticas para recuperação muscular.",
        activitiesCount: 4,
        minCredits: 10,
        partnerType: "class_booking",
        provider: {
          type: "trainer",
          specialties: ["Massagem Desportiva", "Terapia Manual", "Recuperação"],
          certifications: ["Massage Therapist", "Sports Massage"],
          experienceYears: 7,
          bio: "Especialista em massagem desportiva e recuperação muscular.",
        },
        address: "Rua do Príncipe Real 28",
        city: "Lisboa",
        latitude: 38.7189,
        longitude: -9.1482,
        googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=38.7189,-9.1482",
      },
    ],
  },
};

async function seedPartners() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/multisport");

    const allPartners = [];
    for (const category in CATEGORY_PARTNERS) {
      for (const partner of CATEGORY_PARTNERS[category].partners) {
        allPartners.push({ ...partner, category });
      }
    }

    await Partner.insertMany(allPartners, { ordered: false });
    console.log("Partners seeded successfully");
  } catch (e) {
    console.error("Error seeding partners:", e);
  } finally {
    mongoose.disconnect();
  }
}

if (require.main === module) {
  seedPartners();
}

module.exports = { seedPartners };